spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abalasu1/book-app-config.git
  security:
    user:
      name: admin
      password: password
      role: administrator          

server:
  port: 8001
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod