spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abalasu1/book-app.git
          search-paths: 
          - bk-app-config            
  
server:
  port: 8001
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false  
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8002/eureka}
  instance:
    prefer-ip-address: true