spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abalasu1/book-app/application-config   

---
spring:
  profiles: dev
  
server:
  port: 8001
  
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true     
---
spring:
  profiles: prod
  
server:
  port: 9001
  
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true      