spring:
  application:
    name: bk-discovery-service
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
